name: Actions
on: [push]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Ocultos
        run: |
          ls -la
      - name: Clonar
        uses: actions/checkout@v1

      - name: Ocultos despues
        run: |
          ls -la
      - name: Crear Archivo Random
        run: |
          echo $RANDOM >> random.txt
          git add random.txt
          git commit -m "AÃ±adido Random File"
          git push
